### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by Matt-Lepley** [j7isaac/vizil-rpstry#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by xJIsaac** [comment]
I can't for the life of me even get into adding the mobile meta tag because my app doesn't even work anymore. I don't know what happened to it. I keep seeing this...(attached pdf)
[Action Controller: Exception caught.pdf](https://github.com/j7isaac/vizil-rpstry/files/26801/Action.Controller.Exception.caught.pdf)

**Comment by Matt-Lepley** [comment]
This error means that you probably don't have a @quote in the database. Usually whenever you get an undefined method error it is two cases:
1. There is no method 
2. The methods' object is nil (non existent) 

Does this make sense? If you go into your console and manually add a quote to it this error should go away. My assumption is that you destroyed all of your quotes and then this error popped up.

**Comment by xJIsaac** [comment]
You're genius! Thank you sir. That solved it. Now about that mobile meta tag...

**Comment by xJIsaac** [comment]
Ok Matt, I've added the mobile meta tag. I've tested it out and I think I've got it working.

**Comment by Matt-Lepley** [comment]
Thumbs up! Since the issue has been resolved you can close the issue. This is how it works in the real world. :+1:

**Comment by xJIsaac** [comment]
Great! Thanks Matt.
